package;

/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

// @formatter:off
enum FmodSong {
    Fkip;
    LetsGo;
}

enum FmodSFX {
    BallTerrain;
    BallTerrain2;
    FlipperStart;
    FlipperStop;
    KickerEnter;
    KickerLaunch;
    MenuHover;
    MenuSelect;
    Popper;
    Slingshot;
    Slingshot2;
    Slingshot3;
    TunnelEnter;
}

class FmodEvent {
    public static inline extern overload function event(song:FmodSong):String {
        return switch(song) {
            case Fkip: "event:/Music/Fkip";
            case LetsGo: "event:/Music/LetsGo";
        }
    }
    public static inline extern overload function event(sfx:FmodSFX):String {
        return switch(sfx) {
            case BallTerrain: "event:/SFX/Ball/BallTerrain";
            case BallTerrain2: "event:/SFX/Ball/BallTerrain2";
            case FlipperStart: "event:/SFX/Flipper/FlipperStart";
            case FlipperStop: "event:/SFX/Flipper/FlipperStop";
            case KickerEnter: "event:/SFX/Kicker/KickerEnter";
            case KickerLaunch: "event:/SFX/Kicker/KickerLaunch";
            case MenuHover: "event:/SFX/Menu/MenuHover";
            case MenuSelect: "event:/SFX/Menu/MenuSelect";
            case Popper: "event:/SFX/Popper/Popper";
            case Slingshot: "event:/SFX/Slingshot/Slingshot";
            case Slingshot2: "event:/SFX/Slingshot/Slingshot2";
            case Slingshot3: "event:/SFX/Slingshot/Slingshot3";
            case TunnelEnter: "event:/SFX/Tunnel/TunnelEnter";
        }
    }
}
