package;

/*
	DO NOT EDIT THIS FILE DIRECTLY
	This file was generated by a script in FMOD Studio 
 */
// @formatter:off
enum FmodSong {
    Fkip;
    LetsGo;
}

enum FmodSFX {
    FlipperStart;
    FlipperStop;
    MenuHover;
    MenuSelect;
    Slingshot;
    Slingshot2;
    Slingshot3;
    TunnelEnter;
}

class FmodEvent {
    public static inline extern overload function event(song:FmodSong):String {
        return switch(song) {
            case Fkip: "event:/Music/Fkip";
            case LetsGo: "event:/Music/LetsGo";
        }
    }
    public static inline extern overload function event(sfx:FmodSFX):String {
        return switch(sfx) {
            case FlipperStart: "event:/SFX/Flipper/FlipperStart";
            case FlipperStop: "event:/SFX/Flipper/FlipperStop";
            case MenuHover: "event:/SFX/Menu/MenuHover";
            case MenuSelect: "event:/SFX/Menu/MenuSelect";
            case Slingshot: "event:/SFX/Slingshot/Slingshot";
            case Slingshot2: "event:/SFX/Slingshot/Slingshot2";
            case Slingshot3: "event:/SFX/Slingshot/Slingshot3";
            case TunnelEnter: "event:/SFX/Tunnel/TunnelEnter";
        }
    }
}
