package;

/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

// @formatter:off
enum FmodSong {
    Fkip;
    LetsGo;
}

enum FmodSFX {
    BallTerrain;
    BallTerrain2;
    BallConfirm;
    Dropper;
    Dropper2;
    Dropper3;
    FlipperStart;
    FlipperStart2;
    FlipperStop;
    KickerEnter;
    KickerLaunch;
    Light;
    LightComplete;
    MenuHover;
    MenuSelect;
    Popper;
    Popper2;
    Popper3;
    Popper4;
    Slingshot;
    Slingshot2;
    Slingshot3;
    TargetHit;
    TunnelEnter;
    TunnelExit;
}

class FmodEvent {
    public static inline extern overload function event(song:FmodSong):String {
        return switch(song) {
            case Fkip: "event:/Music/Fkip";
            case LetsGo: "event:/Music/LetsGo";
        }
    }
    public static inline extern overload function event(sfx:FmodSFX):String {
        return switch(sfx) {
            case BallTerrain: "event:/SFX/Ball/BallTerrain";
            case BallTerrain2: "event:/SFX/Ball/BallTerrain2";
            case BallConfirm: "event:/SFX/BallConfirm/BallConfirm";
            case Dropper: "event:/SFX/Dropper/Dropper";
            case Dropper2: "event:/SFX/Dropper/Dropper2";
            case Dropper3: "event:/SFX/Dropper/Dropper3";
            case FlipperStart: "event:/SFX/Flipper/FlipperStart";
            case FlipperStart2: "event:/SFX/Flipper/FlipperStart2";
            case FlipperStop: "event:/SFX/Flipper/FlipperStop";
            case KickerEnter: "event:/SFX/Kicker/KickerEnter";
            case KickerLaunch: "event:/SFX/Kicker/KickerLaunch";
            case Light: "event:/SFX/Light/Light";
            case LightComplete: "event:/SFX/Light/LightComplete";
            case MenuHover: "event:/SFX/Menu/MenuHover";
            case MenuSelect: "event:/SFX/Menu/MenuSelect";
            case Popper: "event:/SFX/Popper/Popper";
            case Popper2: "event:/SFX/Popper/Popper2";
            case Popper3: "event:/SFX/Popper/Popper3";
            case Popper4: "event:/SFX/Popper/Popper4";
            case Slingshot: "event:/SFX/Slingshot/Slingshot";
            case Slingshot2: "event:/SFX/Slingshot/Slingshot2";
            case Slingshot3: "event:/SFX/Slingshot/Slingshot3";
            case TargetHit: "event:/SFX/Target/TargetHit";
            case TunnelEnter: "event:/SFX/Tunnel/TunnelEnter";
            case TunnelExit: "event:/SFX/Tunnel/TunnelExit";
        }
    }
}
